name: framework
description: A flutter framework
# don't publish this package yet
publish_to: 'none'
version: 0.5.0
homepage: https://fiesta-labs.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
