name: framework
description: A flutter framework
# don't publish this package yet
publish_to: 'none'
version: 0.2.1
homepage: https://dbx7.net

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
