name: framework
description: A flutter framework
# not a publishable package
publish_to: 'none'
version: 0.6.0
homepage: https://fiesta-labs.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
