name: framework
description: A flutter framework
# don't publish this package yet
publish_to: 'none'
version: 0.2.0
homepage: https://dbx7.net

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
