name: framework
description: A flutter framework
# don't publish this package yet
publish_to: 'none'
version: 0.3.0
homepage: https://fiesta-labs.com

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
